# Generated by Django 4.2.16 on 2024-10-07 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
